In [20]:
import pandas as pd

df = pd.read_csv('/home/student/mycode/challenge/annualcheeseconsumed.txt')

df.head()

,Year,Cheddar,American Other,Mozzarella,Italian other,Swiss,Brick,Muenster,Cream and Neufchatel,Blue,Other Dairy Cheese,Processed Cheese,Foods and spreads,Total American Chese,Total Italian Cheese,Total Natural Cheese,Total Processed Cheese Products
0,1970,5.79,1.20,1.19,0.87,0.88,0.10,0.17,0.61,0.15,0.41,3.32,2.20,7.00,2.05,11.37,5.53
1,1971,5.91,1.42,1.38,0.92,0.94,0.11,0.19,0.62,0.15,0.41,3.55,2.31,7.32,2.29,12.03,5.86
2,1972,6.01,1.67,1.57,1.02,1.06,0.10,0.22,0.63,0.17,0.56,3.51,2.62,7.68,2.59,13.01,6.13
3,1973,6.07,1.76,1.76,1.03,1.06,0.11,0.21,0.66,0.18,0.65,3.31,2.68,7.83,2.80,13.49,5.99
4,1974,6.31,2.16,1.86,1.09,1.18,0.11,0.23,0.70,0.16,0.61,3.42,2.92,8.47,2.95,14.41,6.34

In [21]:
df = df.set_index("Year")
df

,Cheddar,American Other,Mozzarella,Italian other,Swiss,Brick,Muenster,Cream and Neufchatel,Blue,Other Dairy Cheese,Processed Cheese,Foods and spreads,Total American Chese,Total Italian Cheese,Total Natural Cheese,Total Processed Cheese Products
Year,,,,,,,,,,,,,,,,
1970,5.79,1.20,1.19,0.87,0.88,0.10,0.17,0.61,0.15,0.41,3.32,2.20,7.00,2.05,11.37,5.53
1971,5.91,1.42,1.38,0.92,0.94,0.11,0.19,0.62,0.15,0.41,3.55,2.31,7.32,2.29,12.03,5.86
1972,6.01,1.67,1.57,1.02,1.06,0.10,0.22,0.63,0.17,0.56,3.51,2.62,7.68,2.59,13.01,6.13
1973,6.07,1.76,1.76,1.03,1.06,0.11,0.21,0.66,0.18,0.65,3.31,2.68,7.83,2.80,13.49,5.99
1974,6.31,2.16,1.86,1.09,1.18,0.11,0.23,0.70,0.16,0.61,3.42,2.92,8.47,2.95,14.41,6.34
1975,6.04,2.11,2.11,1.12,1.09,0.09,0.24,0.74,0.16,0.57,3.35,3.35,8.15,3.23,14.27,6.69
1976,6.45,2.44,2.31,1.24,1.25,0.09,0.25,0.77,0.18,0.53,3.89,2.59,8.88,3.55,15.51,6.48
1977,6.80,2.42,2.46,1.26,1.21,0.07,0.25,0.80,0.18,0.55,3.88,3.23,9.21,3.72,15.99,7.12
1978,6.94,2.59,2.68,1.37,1.33,0.08,0.27,0.89,0.19,0.51,3.84,3.23,9.53,4.05,16.83,7.07
1979,6.93,2.67,2.80,1.42,1.35,0.06,0.28,0.94,0.18,0.53,3.83,3.12,9.60,4.22,17.16,6.94
1980,6.84,2.78,3.01,1.42,1.32,0.07,0.31,1.00,0.17,0.62,3.96,3.09,9.62,4.42,17.52,7.05
1981,7.03,3.12,2.96,1.47,1.27,0.06,0.29,1.04,0.16,0.78,3.63,3.14,10.15,4.43,18.18,6.77
1982,8.72,2.58,3.24,1.54,1.29,0.06,0.30,1.12,0.16,0.90,4.66,3.29,11.31,4.77,19.90,7.95
1983,9.11,2.50,3.66,1.59,1.25,0.06,0.30,1.15,0.16,0.79,5.09,3.32,11.61,5.26,20.56,8.41
1984,9.54,2.31,4.02,1.72,1.24,0.07,0.32,1.17,0.17,0.91,4.46,3.30,11.85,5.75,21.47,7.76
1985,9.77,2.41,4.60,1.82,1.28,0.08,0.34,1.22,0.17,0.85,4.60,3.00,12.19,6.41,22.54,7.60
1986,9.77,2.35,5.17,1.79,1.29,0.08,0.37,1.33,0.17,0.79,4.77,3.18,12.12,6.96,23.12,7.96
1987,10.61,1.80,5.60,2.01,1.23,0.12,0.38,1.41,0.17,0.77,5.23,3.18,12.40,7.61,24.10,8.41
1988,9.52,1.97,5.99,2.12,1.28,0.10,0.34,1.53,0.17,0.69,4.60,3.75,11.50,8.10,23.71,8.34
1989,9.18,1.85,6.40,2.06,1.23,0.07,0.37,1.61,0.16,0.87,4.61,3.57,11.03,8.46,23.79,8.17
1990,9.05,2.07,6.88,2.04,1.35,0.07,0.40,1.71,0.17,0.87,4.79,3.84,11.13,8.92,24.61,8.63
1991,9.04,1.99,7.15,2.13,1.21,0.06,0.42,1.75,0.16,1.02,4.88,3.75,11.03,9.28,24.94,8.63
1992,9.17,2.09,7.63,2.24,1.18,0.06,0.45,2.00,0.15,0.89,5.19,3.33,11.26,9.86,25.85,8.52
1993,9.07,2.24,7.42,2.23,1.18,0.05,0.45,2.06,0.15,1.18,5.20,3.44,11.31,9.65,26.03,8.64
1994,9.05,2.38,7.76,2.30,1.14,0.05,0.43,2.15,0.16,1.15,5.27,3.44,11.42,10.06,26.55,8.71
1995,9.04,2.65,7.89,2.14,1.09,0.04,0.41,2.04,0.16,1.22,5.44,3.25,11.69,10.03,26.94,8.70
1996,9.19,2.62,8.22,2.14,1.07,0.04,0.39,2.11,0.17,0.88,5.44,3.32,11.81,10.36,27.32,8.75
1997,9.51,2.30,8.16,2.41,0.99,0.03,0.37,2.25,0.18,0.83,4.95,3.05,11.81,10.58,27.54,8.00
1998,9.60,2.38,8.33,2.36,1.01,0.03,0.34,2.20,NaN,1.10,4.45,3.70,11.98,10.68,27.84,8.15
1999,10.01,2.69,8.74,2.28,1.09,0.03,0.28,2.26,NaN,1.21,4.66,3.98,12.70,11.01,29.14,8.64
2000,9.87,2.82,9.05,2.36,1.02,0.03,0.30,2.39,NaN,1.37,4.88,3.19,12.68,11.41,29.79,8.07
2001,9.89,2.93,9.35,2.34,1.12,0.03,0.28,2.21,NaN,1.29,4.27,3.46,12.81,11.69,30.05,7.73
2002,9.76,3.07,9.38,2.43,1.09,0.03,0.28,2.33,NaN,1.44,4.65,3.41,12.83,11.82,30.48,8.06
2003,9.38,3.18,9.45,2.55,1.13,0.03,0.27,2.30,NaN,1.52,4.66,3.61,12.56,12.00,30.52,8.27
2004,10.20,2.66,9.68,2.61,1.20,0.03,0.25,2.34,NaN,1.52,4.06,3.55,12.86,12.29,31.23,7.61
2005,10.15,2.50,9.93,2.73,1.24,0.03,0.26,2.38,NaN,1.55,4.13,3.46,12.65,12.66,31.58,7.59
2006,10.43,2.63,10.11,2.82,1.23,0.03,0.31,2.45,NaN,1.57,4.05,3.71,13.07,12.93,32.43,7.76
2007,10.11,2.68,10.66,2.92,1.24,0.02,0.33,2.49,NaN,1.59,4.09,3.37,12.79,13.58,32.94,7.47
2008,10.22,2.91,10.10,2.95,1.10,0.02,0.37,2.41,NaN,1.45,4.08,2.99,13.13,13.06,32.39,7.08
2009,10.24,3.12,10.08,2.95,1.16,0.03,0.36,2.39,NaN,1.29,3.78,3.21,13.36,13.03,32.48,6.99
2010,10.06,3.24,10.58,2.97,1.18,0.02,0.36,2.30,0.30,1.05,3.53,3.11,13.30,13.54,32.92,6.64
2011,9.59,3.45,10.83,3.15,1.14,0.03,0.44,2.20,0.30,1.19,3.62,3.12,13.04,13.98,33.24,6.74
2012,9.59,3.66,10.69,3.11,1.09,0.04,0.45,2.40,0.30,1.28,3.69,2.92,13.25,13.80,33.51,6.62
2013,9.64,3.71,10.73,3.10,1.00,0.03,0.48,2.46,0.32,1.26,3.63,2.74,13.35,13.83,33.66,6.36
2014,9.85,3.80,11.17,3.02,1.02,0.01,0.47,2.45,0.32,1.31,4.38,2.98,13.65,14.19,34.40,7.36
2015,10.17,3.86,11.27,3.20,1.05,0.01,0.50,2.49,0.32,1.48,4.48,2.84,14.03,14.46,35.35,7.31
2016,10.39,3.95,11.73,3.49,1.06,0.01,0.52,2.61,0.31,1.57,4.85,2.12,14.34,15.21,36.66,6.97
2017,11.07,3.99,11.57,3.49,1.05,0.01,0.53,2.64,0.30,1.49,5.16,1.91,15.06,15.06,37.23,7.07

In [22]:
df = df[['Cheddar', 'Swiss', 'Muenster']]
df.head()

      Cheddar  Swiss  Muenster
Year
1970     5.79   0.88      0.17
1971     5.91   0.94      0.19
1972     6.01   1.06      0.22
1973     6.07   1.06      0.21
1974     6.31   1.18      0.23

In [24]:
df = df.sort_index(ascending=False)
df

      Cheddar  Swiss  Muenster
Year
2017    11.07   1.05      0.53
2016    10.39   1.06      0.52
2015    10.17   1.05      0.50
2014     9.85   1.02      0.47
2013     9.64   1.00      0.48
2012     9.59   1.09      0.45
2011     9.59   1.14      0.44
2010    10.06   1.18      0.36
2009    10.24   1.16      0.36
2008    10.22   1.10      0.37
2007    10.11   1.24      0.33
2006    10.43   1.23      0.31
2005    10.15   1.24      0.26
2004    10.20   1.20      0.25
2003     9.38   1.13      0.27
2002     9.76   1.09      0.28
2001     9.89   1.12      0.28
2000     9.87   1.02      0.30
1999    10.01   1.09      0.28
1998     9.60   1.01      0.34
1997     9.51   0.99      0.37
1996     9.19   1.07      0.39
1995     9.04   1.09      0.41
1994     9.05   1.14      0.43
1993     9.07   1.18      0.45
1992     9.17   1.18      0.45
1991     9.04   1.21      0.42
1990     9.05   1.35      0.40
1989     9.18   1.23      0.37
1988     9.52   1.28      0.34
1987    10.61   1.23      0.38
1986     9.77   1.29      0.37
1985     9.77   1.28      0.34
1984     9.54   1.24      0.32
1983     9.11   1.25      0.30
1982     8.72   1.29      0.30
1981     7.03   1.27      0.29
1980     6.84   1.32      0.31
1979     6.93   1.35      0.28
1978     6.94   1.33      0.27
1977     6.80   1.21      0.25
1976     6.45   1.25      0.25
1975     6.04   1.09      0.24
1974     6.31   1.18      0.23
1973     6.07   1.06      0.21
1972     6.01   1.06      0.22
1971     5.91   0.94      0.19
1970     5.79   0.88      0.17

In [25]:
mean_cheddar = df.loc['1970':'2017', 'Cheddar'].mean()
print(f"Average cheddar consumed from 1970 to 2017: f{mean_cheddar} pounds")

Average cheddar consumed from 1970 to 2017: fnan pounds